### ISSUE TITLE
Autoloot

### ISSUE THREAD

**Issue by ZythDr** [luskanek/Interact#5]
Hi, is it possible to make it so when you have the autoloot patch from vanilla-tweaks (or some other way to decide whether to autoloot or not), that it would also autoloot when using the interact key? currently it doesn't seem to work.

Great DLL mod/tweak anyway, thanks for making this!

**Comment by ZythDr** [comment]
So if Vanilla-Fixes autoloot is disabled, Interact key will autoloot?

**Comment by luskanek** [comment]
Yes, disabling VanillaTweaks auto-loot will enable Interact auto-loot. VanillaTweaks affects the default auto-loot behavior that Interact is also using.
